version: '3.7'

services:
  #
  # Blockchain archive node
  #
  substrate-node:
    image: substrate-client:kusama-latest
    hostname: substrate-node
    build: ./substrate-client
    volumes:
      - 'substrate-data:/data'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: -d /data --unsafe-ws-external --unsafe-rpc-external --rpc-cors all --pruning=archive --name 'Kusama Validator Resource Center V2' --chain kusama
    restart: always
  #
  # SQL data base
  #
  postgres:
    image: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './sql/backend.sql:/docker-entrypoint-initdb.d/backend.sql'
    environment:
      POSTGRES_USER: 'vrc'
      POSTGRES_PASSWORD: 'vrc'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vrc']
      interval: 5s
      timeout: 5s
      retries: 5
    #
    # WARNING: production settings
    # 
    # https://pgtune.leopard.in.ua/#/
    #
    # DB Version: 13
    # OS Type: linux
    # DB Type: dw
    # Total Memory (RAM): 96 GB
    # CPUs num: 16
    # Connections num: 200
    # Data Storage: ssd

    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=24GB"
      - "-c"
      - "effective_cache_size=72GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=500"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=7864kB"
      - "-c"
      - "min_wal_size=4GB"
      - "-c"
      - "max_wal_size=16GB"
      - "-c"
      - "max_worker_processes=16"
      - "-c"
      - "max_parallel_workers_per_gather=8"
      - "-c"
      - "max_parallel_workers=16"
      - "-c"
      - "max_parallel_maintenance_workers=4"

  #
  # Hasura
  #
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8082:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://vrc:vrc@postgres:5432/vrc
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: https://validatorsv2.kusama.polkastats.io
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  #
  # Block crawler
  #
  crawler:
    image: crawler:latest
    build:
      context: ../../
      dockerfile: ./docker/backend/crawler/Dockerfile
    depends_on:
      - 'postgres'
      - 'substrate-node'
    restart: always
    environment:
      - NODE_ENV=production
      - WS_PROVIDER_URL=ws://substrate-node:9944
      - SUBSTRATE_NETWORK=kusama
      # - CRAWLER_RANKING_DISABLE=true
      # - CRAWLER_BLOCK_LISTENER_DISABLE=true
      # - CRAWLER_BLOCK_HARVESTER_DISABLE=true
#
# Persisten volumes
#
volumes:
  db-data: {}
  substrate-data: {}
